baseURL = 'https://example.org/'
languageCode = 'nl-NL'
title = 'Scouting Tibrag Sneek'



[menus]
  [[menus.main]]
    name    = 'Start'
    pageRef = '/'
    weight  = 10

  [[menus.main]]
    name    = 'Groepen'
    pageRef = '/groepen'
    weight  = 20
    
    [[menus.main]]
        name    = 'Dolfijnen'
        pageRef = '/groepen/dolfijnen'
        parent  = 'Groepen'
        weight  = 21
        
    [[menus.main]]
        name    = 'Zeeverkenners'
        pageRef = '/groepen/zeeverkenners'
        parent  = 'Groepen'
        weight  = 22

  [[menus.main]]
    name    = 'Contact'
    pageRef = '/contact'
    weight  = 30

  [[menus.main]]
    name    = 'Leiding'
    pageRef = '/leiding'
    weight  = 40
    
    [[menus.main]]
        name    = 'Leiding linkjes'
        pageRef = '/leiding/leiding-linkjes'
        parent  = 'Leiding'
        weight  = 41
        
    [[menus.main]]
        name    = 'Bestanden'
        pageRef = '/leiding/bestanden'
        parent  = 'Leiding'
        weight  = 42

